[package]
name = "cryptoad"
version = "1.1.0"
authors = ["Kyle Forrester <kyleaforrester@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
